### ISSUE TITLE
根本安装不了?

### ISSUE THREAD

**Issue by aa0604** [ethercap/yii2-ledap#5]
以下根本不存在packagist, 根本搜不到, 为什么还能有三百人安装, 是有我什么不知道 的吗?????
npm-asset/bootstrap-vue: 2.11.0
npm-asset/ledap: ^0.1.8
npm-asset/ledap-vue-bootstrap: ^0.0.4
npm-asset/vue: ^2.6

**Comment by buptlsp** [comment]
composer使用npm或者bower包，是有两种模式的，建议你搜索一下asset-packgist或者 composer asset plugin
