### ISSUE TITLE
坑爹啊, 好不容易安装了, 一看代码, 没有returnApi这个函数

### ISSUE THREAD

**Issue by aa0604** [ethercap/yii2-ledap#6]
应该是少了一个父类, 不知道是没有写还是难度太大了搞不下去了. 你这项目不能用就隐藏啊, 太坑了

**Comment by aa0604** [comment]
> 
> 
> 应该是少了一个父类, 不知道是没有写还是难度太大了搞不下去了. 你这项目不能用就隐藏啊, 太坑了

**Comment by buptlsp** [comment]
哪个地方不能用？
